# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

#encoders dit Symfony d'attendre que les mots de passe dans la base de données seront encodés en bcrypt.
security:
    encoders:
      AppBundle\Entity\User:
        algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      our_db_provider:
          entity:
              class: AppBundle:User
              property: username
        #in_memory:
        #    memory: ~

# Configuration encodage
    encoders:
      #Pas d'encodage avec plaintext
#      Symfony\Component\Security\Core\User\User:
#        algorithm: bcrypt
#        cost: 12
      Symfony\Component\Security\Core\User\UserInterface:
        algorithm: bcrypt
        cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
              #csrf_parameter: _csrf_security_token
              #csrf_token_id: a_private_string
            logout:
              path: /logout
              target: /

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
      - { path: ^/mon-espace, roles: ROLE_USER }